export const LORE_SUBTYPES: Record<string, string> = {
    worldHistory: 'World History',
    timeline: 'Timeline',
    calendar: 'Calendar & Holidays',
    geography: 'Geography & Maps',
    climate: 'Climate & Weather',
    cosmology: 'Cosmology & Planes',
    magic: 'Magic System',
    technology: 'Technology Level',
    pantheon: 'Pantheon & Deities',
    religion: 'Religious Orders',
    mythology: 'Myths & Legends',
    culture: 'Cultural Notes',
    languages: 'Languages & Scripts',
    customs: 'Customs & Traditions',
    festivals: 'Festivals & Celebrations',
    politics: 'Political Systems',
    nobility: 'Noble Houses',
    guilds: 'Guilds & Organizations',
    laws: 'Laws & Legal System',
    trade: 'Trade & Economy',
    currency: 'Currency & Commerce',
    wars: 'Wars & Conflicts',
    disasters: 'Disasters & Catastrophes',
    discoveries: 'Important Discoveries',
    inventions: 'Notable Inventions',
    dynasties: 'Dynasties & Succession',
    races: 'Races & Species',
    monsters: 'Monsters & Creatures',
    wildlife: 'Flora & Fauna',
    dragons: 'Dragons & Ancient Beings',
    artifacts: 'Legendary Artifacts',
    weapons: 'Notable Weapons',
    items: 'Important Items',
    treasures: 'Treasures & Valuables',
    prophecies: 'Prophecies & Omens',
    secrets: 'Hidden Knowledge',
    lore: 'Ancient Lore',
    research: 'Research Notes',
    spells: 'Spells & Rituals',
    alchemy: 'Alchemy & Crafting',
    adventure: 'Adventure Hooks',
    plots: 'Plot Threads',
    npcs: 'Important NPCs',
    rules: 'House Rules',
    references: 'Quick References',
    other: 'Other/Miscellaneous'
};

export const getLoreSubtypeOptions = () =>
    Object.entries(LORE_SUBTYPES).map(([value, label]) => ({ value, label }));

export const getLoreSubtypeLabel = (value: string) => LORE_SUBTYPES[value] ?? value;
